import os
import subprocess
from github import Github
import anthropic

github_token = os.getenv("GITHUB_TOKEN")
anthropic_key = os.getenv("ANTHROPIC_API_KEY")

g = Github(github_token)
repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))

issue_number = int(os.getenv("ISSUE_NUMBER"))
issue = repo.get_issue(number=issue_number)

client = anthropic.Anthropic(api_key=anthropic_key)

prompt = f"""
You are a senior frontend developer.

Fix the issue in the repository.

Issue title:
{issue.title}

Issue description:
{issue.body}

Return the fixed code.
"""

response = client.messages.create(
 model="claude-3-5-sonnet-latest",
    max_tokens=1000,
    messages=[{"role": "user", "content": prompt}]
)

print(response.content)

# create new branch
branch = f"ai-fix-{issue_number}"
subprocess.run(["git", "checkout", "-b", branch])

# example commit
subprocess.run(["git", "add", "."])
subprocess.run(["git", "commit", "-m", f"AI fix for issue #{issue_number}"])

# push branch
subprocess.run(["git", "push", "origin", branch])

# create PR
repo.create_pull(
    title=f"AI Fix: {issue.title}",
    body="Automated fix generated by Claude",
    head=branch,
    base="main"
)