import os
import re
import subprocess
from github import Github, Auth
import anthropic

github_token = os.getenv("GITHUB_TOKEN")
anthropic_key = os.getenv("ANTHROPIC_API_KEY")

g = Github(auth=Auth.Token(github_token))
repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))

issue_number = int(os.getenv("ISSUE_NUMBER"))
issue = repo.get_issue(number=issue_number)

# Get the repository file tree for context
tree = subprocess.run(
    ["git", "ls-files"], capture_output=True, text=True
).stdout.strip()

# Read existing source files to give Claude real context
source_files = {}
for filepath in tree.splitlines():
    if filepath.endswith((".js", ".jsx", ".ts", ".tsx", ".css", ".html")):
        try:
            with open(filepath, "r") as f:
                source_files[filepath] = f.read()
        except Exception:
            pass

files_context = ""
for filepath, content in source_files.items():
    files_context += f"\n--- {filepath} ---\n{content}\n"

client = anthropic.Anthropic(api_key=anthropic_key)

prompt = f"""You are a senior frontend developer. Fix the following issue in the repository.

Issue title: {issue.title}

Issue description:
{issue.body}

Here are the repository files:
{files_context}

Return ONLY the files that need to be changed. For each file, use this exact format:

FILE: <filepath>
```
<full file content>
```

Do not include any other explanation, just the file blocks above.
"""

response = client.messages.create(
    model="claude-sonnet-4-6",
    max_tokens=4096,
    messages=[{"role": "user", "content": prompt}]
)

response_text = response.content[0].text
print(response_text)

# Parse the response and write files
file_pattern = re.compile(r"FILE:\s*(.+)\n```[a-z]*\n(.*?)```", re.DOTALL)
matches = file_pattern.findall(response_text)

if not matches:
    print("No file changes parsed from response. Exiting.")
    exit(1)

for filepath, content in matches:
    filepath = filepath.strip()
    os.makedirs(os.path.dirname(filepath), exist_ok=True) if os.path.dirname(filepath) else None
    with open(filepath, "w") as f:
        f.write(content.strip() + "\n")
    print(f"Wrote: {filepath}")

# Create new branch
branch = f"ai-fix-{issue_number}"
subprocess.run(["git", "checkout", "-b", branch])

# Stage and commit
subprocess.run(["git", "add", "."])
result = subprocess.run(
    ["git", "diff", "--cached", "--quiet"]
)
if result.returncode == 0:
    print("No changes detected after writing files. Exiting.")
    exit(1)

subprocess.run(["git", "commit", "-m", f"AI fix for issue #{issue_number}"])

# Push branch using token-authenticated URL
github_repo = os.getenv("GITHUB_REPOSITORY")
remote_url = f"https://x-access-token:{github_token}@github.com/{github_repo}.git"
subprocess.run(["git", "remote", "set-url", "origin", remote_url])
subprocess.run(["git", "push", "origin", branch])

# Create PR
repo.create_pull(
    title=f"AI Fix: {issue.title}",
    body="Automated fix generated by Claude",
    head=branch,
    base="main"
)
